legislator: "謝衣鳳"
group_name: "罷免缺衣不可 - 謝衣鳯罷免團隊"
social:
  instagram: https://www.instagram.com/bamain_c1feng
  threads: https://www.threads.net/@bamain_c1feng
  facebook: https://www.facebook.com/groups/829936155897331/
links:
  - 網址: https://forms.gle/poDwfnG1FQKfgWBY6
    連結名稱: 志工報名表
